version: '3.4'

services:
  nats-1:
    image: nats
    command: -c /etc/nats-server.conf
    volumes:
      - ./nats-server-1.conf:/etc/nats-server.conf
    ports:
      - 4222:4222
      - 6222:6222
  nats-2:
    image: nats
    command: -c /etc/nats-server.conf
    volumes:
      - ./nats-server-2.conf:/etc/nats-server.conf
    ports:
      - 4223:4222
      - 6223:6222
  nats-3:
    image: nats
    command: -c /etc/nats-server.conf
    volumes:
      - ./nats-server-3.conf:/etc/nats-server.conf
    ports:
      - 4224:4222
      - 6224:6222